[package]
name = "rost_riscv"
version = "0.1.0"
edition = "2021"

[dependencies]
common={path = "./common"}
virtio-drivers = "0.9.0"
flat_device_tree = "3.1.1"
lazy_static = {version = "1.5.0", features = ["spin_no_std"]}
log = "0.4.26"
linked_list_allocator = "0.10.5"
